export const VOLUNTEER_POSITIONS: Array<string> = [
    'Video Editor',
    'UI/UX Designer',
    'Talent Acquisition Specialist',
    'Quality Assurance Auditor',
    'Project Coordinator',
    'Mobile App Developer',
    'Mentorship Program Strategist',
    'Lawyer',
    'International Affairs Specialist',
    'Graphic Designer',
    'Marketing Specialist',
    'Frontend Software Developer',
    'Financial Analyst',
    'Event Coordinator',
    'Dispute Resolution Specialist',
    'Marketing Copywriter',
    'Backend Software Developer',
    'Application and Grants Fund Specialist',
    '3D Animator',
  ]